"""horario_dias_multiples_cascade

Revision ID: 0563c50ff86f
Revises: f3e38afe79e1
Create Date: 2026-04-21 15:22:47.499239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0563c50ff86f'
down_revision: Union[str, None] = 'f3e38afe79e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grupos_semestre', 'horario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('grupos_semestre_horario_id_fkey', 'grupos_semestre', type_='foreignkey')
    op.create_foreign_key(None, 'grupos_semestre', 'horarios', ['horario_id'], ['id'], ondelete='CASCADE')
    op.add_column('horarios', sa.Column('dia_3', sa.String(length=50), nullable=True))
    op.add_column('horarios', sa.Column('dia_4', sa.String(length=50), nullable=True))
    op.alter_column('horarios', 'dia_2',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('horarios', 'dia_2',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('horarios', 'dia_4')
    op.drop_column('horarios', 'dia_3')
    op.drop_constraint(None, 'grupos_semestre', type_='foreignkey')
    op.create_foreign_key('grupos_semestre_horario_id_fkey', 'grupos_semestre', 'horarios', ['horario_id'], ['id'], ondelete='SET NULL')
    op.alter_column('grupos_semestre', 'horario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
