"""semestres_y_carreras

Revision ID: 56be7cc2f2f2
Revises: c5e8a1f3b2d7
Create Date: 2026-04-13 20:19:43.760999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56be7cc2f2f2'
down_revision: Union[str, None] = 'c5e8a1f3b2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('facultad', sa.String(length=255), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('total_semanas', sa.Integer(), nullable=False),
    sa.Column('puntaje_maximo_asistencia', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semestres_id'), 'semestres', ['id'], unique=False)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('dia_1', sa.String(length=50), nullable=False),
    sa.Column('dia_2', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_id'), 'horarios', ['id'], unique=False)
    op.create_table('grupos_semestre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_semestre_id'), 'grupos_semestre', ['id'], unique=False)
    op.add_column('seguimiento_grupos', sa.Column('upload_grupo_ref_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seguimiento_grupos', 'grupos', ['upload_grupo_ref_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed de carreras
    carreras_table = sa.table('carreras',
        sa.column('id', sa.Integer),
        sa.column('nombre', sa.String),
        sa.column('facultad', sa.String),
        sa.column('activa', sa.Boolean)
    )

    op.bulk_insert(carreras_table, [
        {"nombre": "Licenciatura en Administración y Negocios Internacionales", "facultad": "Facultad de Ciencias Empresariales y Jurídicas", "activa": True},
        {"nombre": "Licenciatura en Contaduría Pública", "facultad": "Facultad de Ciencias Empresariales y Jurídicas", "activa": True},
        {"nombre": "Licenciatura en Derecho", "facultad": "Facultad de Ciencias Empresariales y Jurídicas", "activa": True},

        {"nombre": "Licenciatura en Terapia Física y Rehabilitación", "facultad": "Facultad de Ciencias de la Salud", "activa": True},
        {"nombre": "Licenciatura en Enfermería", "facultad": "Facultad de Ciencias de la Salud", "activa": True},
        {"nombre": "Licenciatura en Nutrición y Estilo de Vida", "facultad": "Facultad de Ciencias de la Salud", "activa": True},
        {"nombre": "Médico Cirujano", "facultad": "Facultad de Ciencias de la Salud", "activa": True},
        {"nombre": "Químico Clínico Biólogo", "facultad": "Facultad de Ciencias de la Salud", "activa": True},

        {"nombre": "Ingeniería en Sistemas Computacionales", "facultad": "Facultad de Ingeniería y Tecnología", "activa": True},
        {"nombre": "Ingeniería en Gestión de Tecnologías de la Información", "facultad": "Facultad de Ingeniería y Tecnología", "activa": True},
        {"nombre": "Ingeniería Industrial y de Sistemas", "facultad": "Facultad de Ingeniería y Tecnología", "activa": True},
        {"nombre": "Ingeniería en Electrónica y Telecomunicaciones", "facultad": "Facultad de Ingeniería y Tecnología", "activa": True},

        {"nombre": "Licenciatura en Enseñanza del Inglés", "facultad": "Facultad de Educación", "activa": True},
        {"nombre": "Licenciatura en Enseñanza de las Matemáticas", "facultad": "Facultad de Educación", "activa": True},
        {"nombre": "Licenciatura en Enseñanza de las Ciencias Sociales", "facultad": "Facultad de Educación", "activa": True},
        {"nombre": "Licenciatura en Enseñanza de las Ciencias Naturales", "facultad": "Facultad de Educación", "activa": True},
        {"nombre": "Licenciatura en Enseñanza del Lenguaje y la Comunicación", "facultad": "Facultad de Educación", "activa": True},
        {"nombre": "Licenciatura en Educación Preescolar", "facultad": "Facultad de Educación", "activa": True},
        {"nombre": "Licenciatura en Educación Primaria", "facultad": "Facultad de Educación", "activa": True},

        {"nombre": "Licenciatura en Psicología Educativa", "facultad": "Facultad de Psicología", "activa": True},
        {"nombre": "Licenciatura en Psicología Clínica", "facultad": "Facultad de Psicología", "activa": True},

        {"nombre": "Licenciatura en Teología", "facultad": "Facultad de Teología", "activa": True},

        {"nombre": "Licenciatura en Comunicación y Medios", "facultad": "Escuela de Artes y Comunicación", "activa": True},
        {"nombre": "Licenciatura en Diseño de Comunicación Visual", "facultad": "Escuela de Artes y Comunicación", "activa": True},
        {"nombre": "Licenciatura en Artes Visuales", "facultad": "Escuela de Artes y Comunicación", "activa": True},
        {"nombre": "Licenciatura en Arquitectura", "facultad": "Escuela de Artes y Comunicación", "activa": True},

        {"nombre": "Cirujano Dentista", "facultad": "Escuela de Ciencias Estomatológicas", "activa": True},
        {"nombre": "Técnico Superior Universitario en Tecnología Dental", "facultad": "Escuela de Ciencias Estomatológicas", "activa": True},

        {"nombre": "Licenciatura en Música área Enseñanza Musical", "facultad": "Escuela de Música", "activa": True},
    ])

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seguimiento_grupos', type_='foreignkey')
    op.drop_column('seguimiento_grupos', 'upload_grupo_ref_id')
    op.drop_index(op.f('ix_grupos_semestre_id'), table_name='grupos_semestre')
    op.drop_table('grupos_semestre')
    op.drop_index(op.f('ix_horarios_id'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_semestres_id'), table_name='semestres')
    op.drop_table('semestres')
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.drop_table('carreras')
    # ### end Alembic commands ###
