"""grupo_semestre_sub_bloque

Revision ID: 57b0613b60ca
Revises: 0563c50ff86f
Create Date: 2026-04-21 15:32:42.546697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b0613b60ca'
down_revision: Union[str, None] = '0563c50ff86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_semestre', sa.Column('sub_bloque', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grupos_semestre', 'sub_bloque')
    # ### end Alembic commands ###
