"""grupo_semestre_horario_id_nullable

Revision ID: 76605e6ef952
Revises: 57b0613b60ca
Create Date: 2026-04-21 15:39:59.916994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76605e6ef952'
down_revision: Union[str, None] = '57b0613b60ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grupos_semestre', 'horario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grupos_semestre', 'horario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
