"""upload_upsert_model

Revision ID: 92eff8462d6c
Revises: 56be7cc2f2f2
Create Date: 2026-04-13 20:34:31.252103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92eff8462d6c'
down_revision: Union[str, None] = '56be7cc2f2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('ultima_fecha_subida', sa.Date(), nullable=True),
    sa.Column('ultimo_upload_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_alumnos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_horario_id'), 'uploads_horario', ['id'], unique=False)
    op.add_column('alumnos', sa.Column('grupo_semestre_id', sa.Integer(), nullable=True))
    op.alter_column('alumnos', 'grupo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'alumnos', 'grupos_semestre', ['grupo_semestre_id'], ['id'], ondelete='CASCADE')
    op.add_column('uploads', sa.Column('semestre_id', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('horario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uploads', 'semestres', ['semestre_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'uploads', 'horarios', ['horario_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'horario_id')
    op.drop_column('uploads', 'semestre_id')
    op.drop_constraint(None, 'alumnos', type_='foreignkey')
    op.alter_column('alumnos', 'grupo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('alumnos', 'grupo_semestre_id')
    op.drop_index(op.f('ix_uploads_horario_id'), table_name='uploads_horario')
    op.drop_table('uploads_horario')
    # ### end Alembic commands ###
