"""add_semestre_finalizando

Revision ID: a3dc3b128d32
Revises: aa5d21eed081
Create Date: 2026-04-23 17:20:05.396962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dc3b128d32'
down_revision: Union[str, None] = 'aa5d21eed081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('semestres', sa.Column('finalizando', sa.Boolean(), nullable=True))
    op.execute("UPDATE semestres SET finalizando = FALSE WHERE finalizando IS NULL")
    op.alter_column('semestres', 'finalizando', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semestres', 'finalizando')
    # ### end Alembic commands ###
