"""alumno_activo

Revision ID: aa5d21eed081
Revises: c205d52b9831
Create Date: 2026-04-21 17:36:18.531887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5d21eed081'
down_revision: Union[str, None] = 'c205d52b9831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('activo', sa.Boolean(), nullable=True))
    op.execute("UPDATE alumnos SET activo = True")
    op.alter_column('alumnos', 'activo', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnos', 'activo')
    # ### end Alembic commands ###
