"""semestre_tiene_talleres

Revision ID: c205d52b9831
Revises: 76605e6ef952
Create Date: 2026-04-21 17:34:41.090104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c205d52b9831'
down_revision: Union[str, None] = '76605e6ef952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semestres', sa.Column('tiene_talleres', sa.Boolean(), nullable=True))
    op.execute("UPDATE semestres SET tiene_talleres = False")
    op.alter_column('semestres', 'tiene_talleres', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semestres', 'tiene_talleres')
    # ### end Alembic commands ###
