"""predicciones_ml

Revision ID: f3e38afe79e1
Revises: 92eff8462d6c
Create Date: 2026-04-20 16:43:05.715017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e38afe79e1'
down_revision: Union[str, None] = '92eff8462d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('grupo_nombre', sa.String(length=255), nullable=True),
    sa.Column('prob_riesgo', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('nivel_riesgo', sa.String(length=50), nullable=True),
    sa.Column('prediccion', sa.Integer(), nullable=True),
    sa.Column('semestre_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'alumno_id', name='ix_predicciones_upload_alumno')
    )
    op.create_index(op.f('ix_predicciones_id'), 'predicciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predicciones_id'), table_name='predicciones')
    op.drop_table('predicciones')
    # ### end Alembic commands ###
